---
# tasks file for nginx
- name: install nginx via apt
  ansible.builtin.apt:
    name: "nginx"
    state: "latest"
    update_cache: true
  tags: install_nginx

- name: copy main nginx config file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: config_nginx_main

- name: copy site's nginx config file
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/notls.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: config_nginx_site

- name: copy index.html
  template:
    src: templates/index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: html_copy

- name: ensure nginx is enabled and started
  service:
    name: nginx
    state: started
    enabled: true
  tags: ensure_nginx_started

- name: install firewalld
  package:
    name: firewalld
    state: present
  tags: install_firewalld

- name: insert firewalld rule for nginx
  firewalld:
    port: "{{ nginx_port_no_tls }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  ignore_errors: true
  notify: restart nginx
  tags: firewalld_rule

- name: check web site from control server
  uri:
    url: "https://{{ ansible_host }}"
    validate_certs: no
    return_content: true
  register: webpage
  failed_when: webpage.status != 200
  tags: healthcheck