---
# tasks file for nginx
- name: install nginx via apt
  package:
    name: "nginx"
    state: "latest"
    update_cache: true
  tags: install_nginx

- name: copy main nginx config file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  tags: config_nginx_main

- name: copy site's nginx config file with tls
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/notls.conf
  notify: restart nginx
  tags: 
    - config_nginx_site
    - notest

- name: copy index.html
  template:
    src: templates/index.html.j2
    dest: /usr/share/nginx/html/index.html
  notify: restart nginx
  tags: html_copy

- name: ensure nginx is enabled and started
  service:
    name: nginx
    state: started
    enabled: true
  tags: ensure_nginx_started

- name: install firewalld
  apt:
    name: firewalld
    state: present
    update_cache: true
  notify: restart firewalld
  tags: install_firewalld

- name: ensure firewalld is enabled and started
  service:
    name: firewalld
    state: started
    enabled: true
  tags: ensure_firewalld_started

- name: insert firewalld rule for nginx
  firewalld:
    port: "{{item.port}}/{{item.proto}}"
    permanent: true
    state: enabled
    immediate: true
  ignore_errors: true
  notify: restart nginx
  with_items:
  - {port: "80", proto: "tcp"}
  - {port: "443", proto: "tcp"}
  tags: 
    - firewalld_rule
    - notest

- name: check web site from control server
  uri:
    url: "https://localhost"
    validate_certs: no
    status_code: 200
  tags: 
    - healthcheck
    - notest
    - never