---
- hosts: ubuntu_node
  gather_facts: true
  become: true

  tasks:
  - name: using nginx role with specific tags
    include_role:
      name: nginx
      tasks_from: main.yml
    tags:
      - install_nginx 
      - config_nginx_main
      - config_nginx_site
      - html_copy
      - ensure_nginx_started

  - name: using create_ssl role with specific tags
    include_role:
      name: create_ssl
      tasks_from: main.yml
    tags:
      - ssl_directory
      - generate_open_key
      - generate_csr
      - generate_cert
      - generate_dhparams

  - name: using firewalld role with specific tags
    include_role:
      name: firewalld
      tasks_from: main.yml
    tags:
      - install_firewalld
      - ensure_firewalld_started
      - firewalld_rule
      - healthcheck