---
dependencies: []

galaxy_info:
  author: TheDeathFar
  description: installing nginx with firewalld and configuration for TLS
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.1
  platforms:
    name: Ubuntu
    versions:
      - bionic
      - focal
      - jammy
  galaxy_tags:
    - web 
    - nginx 